### ISSUE TITLE
Only support for python3.7+?

### ISSUE THREAD

**Issue by nadermx** [unoconv/unoserver#1]
Hi, just ported over unoconv, to unoserver.  Thank you.  
Few things, I had an issue trying to install it in a venv with python3.6.and it told me it was not allowed.  Checked your install file and it show's 3.7+ but the documentation doesn't show that?

And also, I don't think sudo is necessary to install the package, as if they make a virtual env, as you show in your tests, with the `--system-site-packages` it uses that python.

**Comment by regebro** [comment]
It might work on Python 3.6 as well, but since support for it ended last year I didn't test that. 

Yes, you are right --system-site-packages uses the system packages and will work of you are installing with the system Python. I added a note about that.
