### ISSUE TITLE
Error code -11 when converting docx to pdf via unoconvert

### ISSUE THREAD

**Issue by fcharrier** [unoconv/unoserver#102]
Hello

I have a strange behavior when calling unoconvert to convert a docx file to pdf: sometimes I receive a -11 error code. The strange point is that I added a retry 10 seconds later, and it works.

This is the logs I get :

`INFO:unoserver:Starting unoconverter.`
`INFO:unoserver:Opening /tmp/1.2.250.1.59.859.2.1276193691.32581.1706138211.442168/1.2.250.1.59.859.2.1276193691.32581.1706138211.442168_012424_232038_cr_tmp.docx`
`INFO:unoserver:Exporting to /tmp/1.2.250.1.59.859.2.1276193691.32581.1706138211.442168/1.2.250.1.59.859.2.1276193691.32581.1706138211.442168_012424_232038_cr.pdf`
`INFO:unoserver:Using writer_pdf_Export export filter`

Is there any documentation which can explains what mean this "-11"?
Is there any possibility to get more logs?

Thanks (and sorry for my poor english),
Fred

**Comment by fcharrier** [comment]
I'm sorry, I have only this result
-11 is the result I get from unoconvert

This is the way I run it:
`proc = subprocess.run(
    [
        "/opt/myproject/bin/unoconvert",
        "--convert-to",
        ext,
        src_path,
        local_dest_path,
    ]
    + extrafilter,
    capture_output=True,
)`

The return code I get is -11, there is no stdout, and I put stderr on my first post

**Comment by regebro** [comment]
I don't think unoconvert should return any error, unless there is a traceback, so this is pretty strange.

**Comment by fcharrier** [comment]
Hum... I'm sorry, I just realized -11 is the output from subprocess.run. This is a known error code : https://stackoverflow.com/questions/24139389/unable-to-find-out-what-return-code-of-11-means

But it means unoconvert crashed (Seg fault), without any output except the one I wrote

Maybe a duplicate of https://github.com/unoconv/unoconv/issues/306 ?

**Comment by regebro** [comment]
No, that's libreoffice crashing, the unoconvert doesn't start that. Which would mean python had a segfault? That seems highly unusual. What happens if you just run that command from the commandline?

**Comment by fcharrier** [comment]
I'm sorry, I can't help a lot, I left the company I was working for when I created this issue.
I sent a message to my old colleagues about our discussion.
