### ISSUE TITLE
Details about concurrent executions of unoconv in the README could be useful

### ISSUE THREAD

**Issue by vgu-natbraille** [unoconv/unoserver#103]
The README does not mention what happens when multiple concurrent executions of unoconv are run. Are they queued (Then what happens if a conversion takes a long time)  ? Are they Executed concurrently ? Or should concurrent executions even no attempted ? It would be nice if some info was added in the README. Thanks !

**Comment by regebro** [comment]
Well, I don't know, why don't you try it and see? :-D

**Comment by vgu-natbraille** [comment]
Well, I would prefer not to "try and see" : my tests might only work because I don't encounter some race condition, and not work in the general case. That's why I would prefer the authors to give me an informed answer.

A few years ago, I implemented a converter based on libreoffice headless server but but it showed to be so unreliable that I ended up spawning a LibreOffice instance for each transcription :-D

**Comment by regebro** [comment]
This isn't an issue that is straightforward enough to give a definitive answer that will be correct over different situations and operating systems and network situations and dockers, etc. But, the XMLRPC server should deal with the requests it receives in order. I don't know what the limit to this is, or if there is one, and I can't promise this will always work, but at least, on a standard Linux system, it just works.

**Comment by regebro** [comment]
The XMLRPC server is written in Python and is a part of the python standard library.

The conversions will be done sequentially.
