### ISSUE TITLE
Unoserver Hangs randomly

### ISSUE THREAD

**Issue by kotso** [unoconv/unoserver#108]
I have issue with Unoserver + Libreoffice.

Randomly Unoserver stops responding to it's port (telnet fails) and same time libreoffice process started by unoserver using 100% of  single core, constantly. Waited more then hour and it never ended, solution is only to restart Unoserver.

Any idea how to debug issue or how to make libreoffice log errors? 

Environment is:
- Almalinux 9.3
- Libreoffice 7.1.8.1-11 from Almalinux AppStream repository
- Python 3.9
- Unoserver 2.0.1

Unoserver running under systemd service with following systemd unit configuration file:

```
[Unit]
Description=unoserver
After=network.target

[Install]
WantedBy=multi-user.target

[Service]
Type=simple
User=root
Group=root
ExecStart=/usr/local/bin/unoserver --interface 0.0.0.0 --uno-interface 0.0.0.0  --port 2003  --uno-port 2002
Environment=PYTHONUNBUFFERED=true
KillSignal=SIGKILL
Restart=on-failure
RestartSec=1
```

I have added `KillSignal=SIGKILL` to make service restart quickly.

Will appreciate any recommendation how to debug this issue.

**Comment by kotso** [comment]
ok, after some more digging came up to fact that there are certain files that cause this issue.

uploading one of such here.

First idea about file is that it can be because of Unicode characters, but not, this document is made of one template, and other files then these work perfect with unoserver.

@regebro will appreciate any idea how to debug it further. 

like I have multiple files that work, and this single once that causes things to fail.
[03-1111-contract.docx](https://github.com/unoconv/unoserver/files/14511884/03-1111-contract.docx)

**Comment by regebro** [comment]
I couldn't replicate it, it might be dependent on Libreoffice version. I was using 7.3.7.2. Or maybe it could be a font issue?
