### ISSUE TITLE
unoserver sometimes generates errored PDF files without crashing

### ISSUE THREAD

**Issue by niels-bosman** [unoconv/unoserver#109]
We've noticed that some of our users are experiencing invalid PDF's being generated form our unoserver-server. I will attach a document that is crashed to demonstrate (OUTPUT.pdf). I have noticed the following things when this happens:

- The file is always 32 bytes
- The file always contains `unoconvert error: signal: killed` as raw data (invalid PDF of course).
- This randomly happens to us, we would expect the converting to fail and there to be no result

How can we prevent this kind of behaviour from happening and possibly prevent this?

[INPUT.pptx](https://github.com/unoconv/unoserver/files/14622733/INPUT.pptx)
[OUTPUT.pdf](https://github.com/unoconv/unoserver/files/14622734/OUTPUT.pdf)

**Comment by regebro** [comment]
For me it does print an "ioerror" indicating that something is wrong with the input file. It does generate an output file anyway, though. That was with Libreoffice 7.3.7.2.

**Comment by regebro** [comment]
Hmm, I wonder if "unoconvert error: signal: killed" means the OS killed it because it used too many resources, maybe?
