### ISSUE TITLE
Conversion errors when running in Docker containers

### ISSUE THREAD

**Issue by cccs-rs** [unoconv/unoserver#111]
Hi there!

We seem to run into an issue where we're able to convert at least one document when the container starts but subsequent requests to convert a file (even if it's the same file), result in an error which seems to elude to a permissions issue with writing (similar to https://github.com/unoconv/unoserver/issues/40). However, in our case we perform all writes to a subdirectory within `/tmp` which our user has access to so it shouldn't be permissions-related. The only way to convert another document is to restart the container/pod or kill the server process and start it again.

I've noticed the same phenomenon happens when using unoconv with a pre-existing listener (rather than have it start up one every time we make a conversion request), so perhaps the same issue moved to the rewrite of unoserver?

For the moment, we're using unoconv in our [document preview service in Assemblyline](https://github.com/CybercentreCanada/assemblyline-service-document-preview) but the current implementation is too slow to keep up with high volume workloads (considering we're constantly starting up a new listener on request), so we'd love to move over to unoserver but this is what currently prevents us from doing so.

If there's anything you can suggest, it would be greatly appreciated.

**Comment by regebro** [comment]
The exact error message would be good, and also the command line to unocovert.
