### ISSUE TITLE
Sometimes I get xmlrpc.client.Fault: <Fault 1: "<class 'unoserver.converter.com.sun.star.connection.NoConnectException'>:Connector : couldn't connect to socket (Connection refused) at ./io/source/connector/connector.cxx:118">

### ISSUE THREAD

**Issue by xlmnxp** [unoconv/unoserver#116]
I'm running unoserver in docker and some times I receive the following error
```
xmlrpc.client.Fault: <Fault 1: "<class 'unoserver.converter.com.sun.star.connection.NoConnectException'>:Connector : couldn't connect to socket (Connection refused) at ./io/source/connector/connector.cxx:118">
```

and the conversation failed

**Comment by regebro** [comment]
I get that if I call the convert client before libreoffice has fully started, which takes a few seconds. Do you get it at other times?

**Comment by xlmnxp** [comment]
> I get that if I call the convert client before libreoffice has fully started, which takes a few seconds. Do you get it at other times?

Is there way to make unoconvert to wait until unoserver be ready or libreoffice fully loaded?

**Comment by regebro** [comment]
There wasn't before, but with the 2.0 refactor, there may be. Or rather, the server can now make calls, and if they fail, just wait a bit.

**Comment by xlmnxp** [comment]
@regebro is the option available now?

**Comment by regebro** [comment]
It is now.
