### ISSUE TITLE
Introducing timeout and retrying mechanism

### ISSUE THREAD

**Issue by HirotoKagotani** [unoconv/unoserver#119]
I am using unoserver/unoconvert with Moodle LMS. (See [MDL-75066](https://tracker.moodle.org/browse/MDL-75066))
Moodle uses unoserver to convert assignment submission files into pdf.
Students may submit various types of document files.
LibreOffice (soffice.bin) sometimes keeps 100% CPU usage and XMLRPC never finishes depending on input file characteristics and/or some specific conditions.

My proposal is introducing timeout and retrying mechanism for such situation.
On detecting timeout, unoserver may kill and restart LibreOffice within a certain limited number of times.
On exceeding the number limit, unoserver may return an error.

Thank you and regards,

**Comment by regebro** [comment]
I think that could be a good feature to have, indeed.

**Comment by regebro** [comment]
Implemented in the latest version.
