### ISSUE TITLE
Ship systemd unit file with unoserver

### ISSUE THREAD

**Issue by WilliamDEdwards** [unoconv/unoserver#12]
It's likely that the most common use case would be to run `unoserver` in the background as a daemon. Shipping a systemd file (either packaged or in the README) would allow users to easily implement this.

Adding systemd support to the code itself (such as sending `READY=1` at start time) would allow for using systemd's full potential, i.e. by using the 'Notify' type.

**Comment by mara004** [comment]
> It's likely that the most common use case would be to run unoserver in the background as a daemon.

`unoserver` loads the full libreoffice app into memory, which may not be generally desirable to do. Therefore, it should only be running as long as it is really needed. I don't think an automatically started background daemon is suitable for this case at all.

Moreover, `unoserver` code should clearly not require systemd, as it is intended to be a cross-platform library.

**Comment by WilliamDEdwards** [comment]
> > It's likely that the most common use case would be to run unoserver in the background as a daemon.
> 
> unoserver loads the full libreoffice app into memory, which may not be generally desirable to do. Therefore, it should only be running as long as it is really needed. I don't think an automatically started background daemon is suitable for this case at all.

Eh, [isn't that's the whole idea](https://github.com/unoconv/unoserver#overview)?

> 
> > Adding systemd support to the code itself (such as sending READY=1 at start time) would allow for using systemd's full potential
> 
> unoserver code should clearly not require systemd, as it is intended to be a cross-platform library.

It is not said anywhere that it should be required.

**Comment by mara004** [comment]
> Eh, isn't that's the whole idea?

Not quite. The idea is to start unoserver when you need it, then convert a batch of files, and then stop it again. Not to generally keep it as background task all the time.

> It is not said anywhere that it should be required.

A phrase like `Adding systemd support to the code itself` sounds a lot like systemd would be required, or at least that development would be centered towards Linux.

**Comment by WilliamDEdwards** [comment]
> > It is not said anywhere that it should be required.
> 
> A phrase like `Adding systemd support to the code itself` sounds a lot like systemd would be required, or at least that development would be centered towards Linux.

If the systemd notification socket is not available, message should be discarded.

**Comment by mara004** [comment]
While it may theoretically be possible to integrate platform-specific systemd support into unoserver, I don't think this makes any sense. There are other cross-platform means to start, invoke, and stop unoserver as needed.
I don't see a reason for adding systemd-related code, given that unoserver is not intended as an auto-started daemon, but rather as an on-demand tool, as I already explained. If you personally want to use unoserver as general background daemon and don't mind the RAM overhead, you are of course free to do this, but you should acknowledge that this is your non-standard, Linux-specific use case.
There are simple, cross-platform ways to detect from Python code when unoserver is ready, so there is no need for using a systemd signal, really.

**Comment by regebro** [comment]
I don't know anything about systemd, and it's not high on my list of things to learn. So that would probably be a "no".

**Comment by WilliamDEdwards** [comment]
> I don't know anything about systemd, and it's not high on my list of things to learn. So that would probably be a "no".

I can create a PR if it's welcome.

**Comment by regebro** [comment]
The problem with that is that it's hard to maintain if I don't understand it. So it's welcome, but I'm a bit worried it would be a wasted effort. But if it's a 10 minute job or so, then that would be great.

**Comment by WilliamDEdwards** [comment]
> The problem with that is that it's hard to maintain if I don't understand it. So it's welcome, but I'm a bit worried it would be a wasted effort. But if it's a 10 minute job or so, then that would be great.

If you choose not to add systemd support to the code, it'd be something like:

```
[Unit]
Description=unoserver
After=network.target

[Install]
WantedBy=multi-user.target

[Service]
Type=simple
User=unoserver
Group=unoserver
ExecStart=/usr/local/bin/unoserver
Environment=PYTHONUNBUFFERED=true
Restart=on-failure
RestartSec=60
```

... but seeing as how the `unoserver` binary could be installed anywhere, this should be no more than an example.
