### ISSUE TITLE
Option to Bind Domain Socket

### ISSUE THREAD

**Issue by pg-wtatum** [unoconv/unoserver#121]
Is there an option to have unoserver bind to a unix domain socket instead of a network interface? Might not make much practical difference in terms of security or performance but my preference is to use a domain socket over a network listener whenever possible so just curious if this option is available or if it's practical to add?

**Comment by regebro** [comment]
What is the usecase? If it's on the same machine you could just use a file. 

And in fact, because of another issue, it's likely that even the streaming will end up being actually written to temporary files on the server side anyway.

**Comment by pg-wtatum** [comment]
No different than the ordinary use-case. I would still anticipate using a file. This is more about having unoserver listen for incoming control signals on a domain socket rather than on 2003 in order to avoid binding the port. Likewise I was curious of LibreOffice had the option to bind UNO on a domain socket instead of 2002 as well but I struggled to find anything in their docs about it.

**Comment by regebro** [comment]
LibreOffice only supports sockets and named pipes.

**Comment by regebro** [comment]
As LibreOffice doesn't support domain sockets I don't think we want to bother implementing this for the unoserver part. The benefit is minimal, at best.
