### ISSUE TITLE
Install Questions run unoserver.server  No such file or directory: 'libreoffice'

### ISSUE THREAD

**Issue by roc26002w** [unoconv/unoserver#123]
I'm run `python3 find_uno.py` check success 

but run `python3 -m unoserver.server` get  
`FileNotFoundError: [Errno 2] No such file or directory: 'libreoffice'`

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/a0a59bc5-b547-485a-9ce9-9e1e41eb7a1c">

## OS info
* AlamaLinux 9
* LibreOffice 24.2.5.2 bffef4ea93e59bebbeaf7f431bb02b1a39ee8a59
* Python 3.9.18
* pip 21.2.3 from /home/deploy/.local/lib/python3.9/site-packages/pip (python 3.9)

**Comment by regebro** [comment]
It doesn't find the libreoffice executable, which is strange as the uno library is installed. But anyway, you can specify that executable with the "--executable" parameter.

**Comment by regebro** [comment]
--executable should be the libreoffice executable.

**Comment by roc26002w** [comment]
oh, I see.   
`python3 -m unoserver.server --executable  /opt/libreoffice24.2/program/soffice`

work for me.  
THX
