### ISSUE TITLE
Auto-formatting text

### ISSUE THREAD

**Issue by DaniilAbdulov** [unoconv/unoserver#127]
Is it possible to specify the grammar checking language? By default, after downloading a document in docx format, users are set to the verification language - English. I need to change to any other, for example, German. My request looks something like this:
      url: `${
        config.unoserverUrl
      }?convert_to=${convertTo}&infiltername=${infiltername}&filtername=${filtername}`,
      encoding: null,
      formData: {
        file: {
          value: content,
          options: {
            filename: sourceFilename,
            contentType: 'text/html'
          }
        }
      },
      returnStream: true

**Comment by regebro** [comment]
Unoserver is for file format conversion, I think this is out of scope.
