### ISSUE TITLE
Run converter as a module

### ISSUE THREAD

**Issue by ntoniazzi** [unoconv/unoserver#132]
Hello,
I read in the README that the three scripts can be run a modules, which I find useful.
So I tried with the server : `/path/to/libreoffice/program/python -m unoserver.server -h` and it works fine.
But the converter and comparer fail silently : `/path/to/libreoffice/program/python -m unoserver.converter -h`.
Did I miss something?

I checked with version 2.2.2.

Thanks.

**Comment by regebro** [comment]
Ah, yes, that is no longer correct for the client. I will update that.

The clients also no longer needs to be run with with the LibreOffice provided Python, so the need for running them this way is gone.

**Comment by ntoniazzi** [comment]
Thanks.
