### ISSUE TITLE
The unoconvert module needs to be separated from the unoserver project.

### ISSUE THREAD

**Issue by aizpy** [unoconv/unoserver#133]
Currently, the unoconvert module is included in the unoserver project. If I deploy unoserver on Machine A using Docker, in order to access this service on Machine A, I must also install unoserver on Machine B to use unoconvert. Normally, it would be nice if I deploy a server on Machine A, all I need on Machine B is a client to access it.

Moreover, since unoserver depends on LibreOffice, Unoserver needs to be installed by and run with the same Python installation that LibreOffice uses. However, unoconvert should only depend on whether the remote unoserver is running, so there should not be so many restrictions when installing the unoconvert module.

**Comment by regebro** [comment]
You don't need Libreoffice to install unoserver, or run the unoconvert module. It's only needed when running unoserver.
