### ISSUE TITLE
Add timeout to client

### ISSUE THREAD

**Issue by lafrech** [unoconv/unoserver#137]
When server is down, a `ConnectionRefusedError` ultimately bubbles up.

It would be nice if the `convert` and `compare` methods had a timeout argument to handle this gracefully and return a dedicated exception.

**Comment by regebro** [comment]
I think this should be solved in the next release.

**Comment by lafrech** [comment]
> I think this should be solved in the next release.

Did you mean in 3.x?

Because I don't see anything regarding client timeout.

I saw the `--conversion-timeout` added to the server, but I don't think there's been any change to the client regarding this.

I just tested and got two different errors:

- `xmlrpc.client.Fault: <Fault 1: "<class 'TimeoutError'>:">`
- `ConnectionRefusedError: [Errno 111]`

**Comment by regebro** [comment]
No, the bubbling up of a connectionerror is now handled correctly. That
shouldn't be timed out, it's a genuine unrecoverable error.
