### ISSUE TITLE
Can't convert pdf to word

### ISSUE THREAD

**Issue by Feniksss** [unoconv/unoserver#14]
receive the error 
`could not find an export from com.sun.star.drawing.DrawingDocument to writer_MS_Word_2007`

I tested with any pdf documents. The libreoffice command works perfect.

**Comment by Feniksss** [comment]
Example of PDF attached
[test.pdf](https://github.com/unoconv/unoserver/files/7905420/test.pdf)

**Comment by regebro** [comment]
When I do this with LibreOffice I get the same error:

```$ soffice --convert-to docx reportFileTypes.pdf 

Error: no export filter for /home/lregebro/Shoobx/unoserver/reportFileTypes.docx found, aborting.
Error: no export filter
```

**Comment by sandhya-sago** [comment]
Try this
`soffice  --infilter="writer_pdf_import" --convert-to docx test.pdf`
