### ISSUE TITLE
CSV filter options are ignored

### ISSUE THREAD

**Issue by daniele-athome** [unoconv/unoserver#149]
Or maybe I'm doing it wrong :-)

```
unoconvert --convert-to 'csv' --output-filter 'Text - txt - csv (StarCalc)' --filter-options 'FilterOptions=59,34,76,1' --verbose input.xls output.csv
```

However the separator in the csv file is always comma instead of the provided one (semicolon, 59). I don't know if the right filter option name is "FilterOptions" (I tried to adapt an old `unoconv` command line), however [the csv filter](https://help.libreoffice.org/latest/en-US/text/shared/guide/csv_params.html) doesn't have any named options, only positional ones.

Thanks for your help!

**Comment by regebro** [comment]
I released version 3.1 where you can use `--filter-options 59,34,76,1`.
