### ISSUE TITLE
Unoserver ran once and don't restart

### ISSUE THREAD

**Issue by classifaddict** [unoconv/unoserver#18]
Hello,
I succeed running unoserver/unoconverter once and then I never been able to start the server again after rebooting the machine:

$ sudo unoserver --daemon --executable /usr/lib/libreoffice/program/soffice.bin
INFO:unoserver:Starting unoserver.
INFO:unoserver:Command: /usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/tmpznzt5utn --accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
<subprocess.Popen object at 0x7fd1c8c1ad60>

$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0   8940   160 ?        Ssl  08:04   0:00 /init
root         9  0.0  0.0   8948   140 tty1     Ss   08:04   0:00 /init
olivier     10  0.0  0.0  18228  2772 tty1     S    08:04   0:00 -bash
root        76  0.0  0.0   8948   140 tty2     Ss   08:06   0:00 /init
olivier     77  0.0  0.0  18480  3324 tty2     S    08:06   0:01 -bash
olivier    805  0.0  0.0  18664  1888 tty2     R    10:45   0:00 ps aux

$ unoconvert --convert-to pdf test.fodt test.pdf
INFO:unoserver:Starting unoconverter.
Traceback (most recent call last):
  File "/usr/local/bin/unoconvert", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/unoserver/converter.py", line 231, in main
    converter = UnoConverter(args.interface, args.port)
  File "/usr/local/lib/python3.8/dist-packages/unoserver/converter.py", line 74, in __init__
    self.context = self.resolver.resolve(
unoserver.converter.NoConnectException: Connector : couldn't connect to socket (Connection refused) /build/libreoffice-crGbO6/libreoffice-7.3.0~rc3/io/source/connector/connector.cxx:117

This happened in both Ubuntu 20.04.3 WSL and Virtualbox.

Is there anything that could prevent unoserver from restarting?

Thanks for this tools and your help!

**Comment by regebro** [comment]
Try without `--daemon` and see what happens. Maybe it crashes?

**Comment by classifaddict** [comment]
$ sudo unoserver --executable /usr/lib/libreoffice/program/soffice.bin
[sudo] password for olivier:
INFO:unoserver:Starting unoserver.
INFO:unoserver:Command: /usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/tmp8ip81ibp --accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext

Is there a log file somewhere?

**Comment by classifaddict** [comment]
unoconvert is OK if I run this command in a separate shell:
/usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nologo --nofirststartwizard --norestore -env:UserInstallation=file:///tmp/tmp8ip81ibp --accept="socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext"

**Comment by regebro** [comment]
Since that is literally all Unoserver does, I can't explain that.

**Comment by classifaddict** [comment]
Weird! I will let you if I find an explanation.
Thanks.

**Comment by unbranched** [comment]
Had the same problem, solved by doing:

$ unoserver --daemon --executable /usr/lib/libreoffice/program/soffice

Please note it's not soffice.bin, and please don't start it with sudo!

Then unoconvert worked. Tested in a python virtual env.

**Comment by regebro** [comment]
Normally unoserver just calls `libreoffice`, but unless you have a broken install somewhere, that would be `/usr/lib/libreoffice`, which is a symlink to `/usr/lib/libreoffice/program/soffice`, so I'm curious to why `--executable /usr/lib/libreoffice/program/soffice` would make a difference.

**Comment by unbranched** [comment]
> Normally unoserver just calls `libreoffice`, but unless you have a broken install somewhere, that would be `/usr/lib/libreoffice`, which is a symlink to `/usr/lib/libreoffice/program/soffice`, so I'm curious to why `--executable /usr/lib/libreoffice/program/soffice` would make a difference.

Yes it works too without specifying the executable.
I specified that in case the OP needs it.

**Comment by regebro** [comment]
True, they specified soffice.bin, I'll try to remember that if somebody else has this issue.
