### ISSUE TITLE
Fail to convert some doc files to pdf files

### ISSUE THREAD

**Issue by kartikeyporwal** [unoconv/unoserver#2]
Hi, thanks for developing and sharing this project.

I recently came across an issue while converting a `.doc` file to a `.pdf` file (unfortunately, I can't share doc file due to IP reasons).

The error was: [`RuntimeError: The input document is of an unknown document type. This is probably a bug.`](https://github.com/unoconv/unoserver/blob/31cc14eb970866fce7ec95a158556455aae2c28d/src/unoserver/converter.py#L49-L52)

Though I'm not familiar with the [OpenOffice APIs](https://www.openoffice.org/api/docs/common/ref/com/sun/star/document/module-ix.html), when I checked [`document.SupportedServiceNames`](https://github.com/unoconv/unoserver/blob/31cc14eb970866fce7ec95a158556455aae2c28d/src/unoserver/converter.py#L153-L155) for that particular file, the result is `('com.sun.star.document.OfficeDocument', 'com.sun.star.text.GenericTextDocument', 'com.sun.star.text.WebDocument')`.
Neither of these are listed in [`DocTypes`](https://github.com/unoconv/unoserver/blob/31cc14eb970866fce7ec95a158556455aae2c28d/src/unoserver/converter.py#L26-L34). When I added `com.sun.star.document.OfficeDocument` in `DocTypes`, the new error states [`RuntimeError: Could not find an export filter from com.sun.star.document.OfficeDocument to pdf_Portable_Document_Format`](https://github.com/unoconv/unoserver/blob/31cc14eb970866fce7ec95a158556455aae2c28d/src/unoserver/converter.py#L183-L185).

Now when I checked the `DocumentService` of [`export_filter`](https://github.com/unoconv/unoserver/blob/31cc14eb970866fce7ec95a158556455aae2c28d/src/unoserver/converter.py#L97), there is no entry for `com.sun.star.document.OfficeDocument`, and `com.sun.star.text.GenericTextDocument` but `com.sun.star.text.WebDocument`, so I replaced `com.sun.star.document.OfficeDocument` in `DocTypes` with `com.sun.star.text.WebDocument` but later found `com.sun.star.text.WebDocument` is [deprecated](https://www.openoffice.org/api/docs/common/ref/com/sun/star/text/WebDocument.html).

Fortunately, It worked.

But my concern is, can this project be ported to support any kind of docs (`.doc`, `.docx`, `.odt`, `.rtf`, etc.) conversion to pdf? 
Though the changes I made worked for the documents I have but I am afraid as
1. `com.sun.star.text.WebDocument` is deprecated
2. There might come some other type of `.doc` file which can fail during pdf cnversion.

I guess some change in [`export_filters`](https://github.com/unoconv/unoserver/blob/31cc14eb970866fce7ec95a158556455aae2c28d/src/unoserver/converter.py#L91-L93) query might include `DocumentService` for other `DocTypes`.

Thanks!

**Comment by regebro** [comment]
That's strange, why is that doc file not supported as a TextDocument?
Is it not a word document?

**Comment by kartikeyporwal** [comment]
Yes, I later found out that it was not the original word format but `com.sun.star.text.WebDocument` that is a html type of format with `.doc` extension.

**Comment by regebro** [comment]
I see. I'll see if I can find some example of that and test it, it's possible that adding com.sun.star.text.WebDocument isn't a problem.

**Comment by regebro** [comment]
I can't find any examples of this document format. However, the export filter list does list a "com.sun.star.text.WebDocument" to "pdf_Portable_Document_Format" output filter, so it should be possible to convert it.

**Comment by regebro** [comment]
I think the changes made in the next release will solve this issue.

**Comment by regebro** [comment]
1.2 released
