### ISSUE TITLE
How can i use custom filter in convertation?

### ISSUE THREAD

**Issue by HavingNoFuture** [unoconv/unoserver#24]
Hello! Nice job!

I want use `HTML (StarWriter):EmbedImages` filter for convertation like:
`libreoffice --convert-to "html:HTML (StarWriter):EmbedImages" --outdir outdir_path file.docx`

How can i use this filter with `unoconvert`?

My solution:
`unoconvert --convert-to html:HTML (StarWriter):EmbedImages file.docx outdir_path`
Doesn't work: 
`RuntimeError: Unknown export file type, unknown extension 'html:HTML (StarWriter):EmbedImages'
`

**Comment by regebro** [comment]
Yeah, you can't, but it would be nice if you could. Marking this as a Feature request.

**Comment by lfglopes** [comment]
I would also be interested in this possibility.

**Comment by asmundstavdahl** [comment]
#59 implemented :)
