### ISSUE TITLE
desktop.loadComponentFromURL works slow

### ISSUE THREAD

**Issue by i4never** [unoconv/unoserver#27]
Hi all.
I'm trying to convert MS Word(.doc) file to txt. The output is fine but it takes centuries. After some digging (add timing to uno related call), it seems `self.desktop.loadComponentFromURL` is very slow. I import `unoserver.converter` and run `convert` several times, the first five `self.desktop.loadComponentFromURL` took 19.27s, 50.96s, 83.38s, 114.64s, 144,44s. Am I doing sth wrong?

**Comment by i4never** [comment]
By the way, I'm using docker hosted on OS X. Unoserver and client are running in the same container.

**Comment by regebro** [comment]
No, the document is loading just takes a long time to load. It's possible having more memory would speed things up, but I don't actually know. It's a Libreoffice issue in any case.

**Comment by 96imranahmed** [comment]
Hey @i4never, did you ever manage to find a solve for this? Also on docker hosted on OS X and noticing that a tiny file takes ages to load. I don't think we'd be able to use this service on our app if it takes this long to process a call...

**Comment by i4never** [comment]
Hi @96imranahmed, sadly no. The same problem is also happening on gotenberg which also use libreoffice as backend through api. It seems to be a libreoffice issue.
