### ISSUE TITLE
Stacktrace when converting some files 

### ISSUE THREAD

**Issue by Rafiot** [unoconv/unoserver#33]
It's not directly a problem with unoserver, but I have no idea how to efficiently report that to the libreoffice folks/people doing packaging for ubuntu.

Some files (I can mostly reproduce it with XLS files) cause a stack-trace that look like that: 
```
Fatal exception: Signal 6
Stack:
/usr/lib/libreoffice/program/libuno_sal.so.3(+0x3ffc3)[0x7f80bb86ffc3]
/usr/lib/libreoffice/program/libuno_sal.so.3(+0x4013a)[0x7f80bb87013a]
/lib/x86_64-linux-gnu/libc.so.6(+0x43090)[0x7f80bb675090]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f80bb67500b]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f80bb654859]
/usr/lib/libreoffice/program/libmergedlo.so(+0x1219b92)[0x7f80bcab2b92]
/usr/lib/libreoffice/program/libmergedlo.so(_ZN11Application5AbortERKN3rtl8OUStringE+0x98)[0x7f80bea12ed8]
/usr/lib/libreoffice/program/libmergedlo.so(+0x21c6026)[0x7f80bda5f026]
/usr/lib/libreoffice/program/libmergedlo.so(+0x3181ec1)[0x7f80bea1aec1]
/usr/lib/libreoffice/program/libuno_sal.so.3(+0x18832)[0x7f80bb848832]
/usr/lib/libreoffice/program/libuno_sal.so.3(+0x400a7)[0x7f80bb8700a7]
/lib/x86_64-linux-gnu/libc.so.6(+0x43090)[0x7f80bb675090]
/usr/lib/libreoffice/program/libmergedlo.so(_ZNK3vcl6Window9GetCursorEv+0x4)[0x7f80be7473a4]
/usr/lib/libreoffice/program/libmergedlo.so(+0x276cfba)[0x7f80be005fba]
/usr/lib/libreoffice/program/libmergedlo.so(_ZN9Scheduler22CallbackTaskSchedulingEv+0x2fb)[0x7f80bea0372b]
/usr/lib/libreoffice/program/libmergedlo.so(_ZN14SvpSalInstance12CheckTimeoutEb+0x10e)[0x7f80beb835ce]
/usr/lib/libreoffice/program/libmergedlo.so(_ZN14SvpSalInstance7DoYieldEbb+0x8b)[0x7f80beb836db]
/usr/lib/libreoffice/program/libmergedlo.so(+0x3179872)[0x7f80bea12872]
/usr/lib/libreoffice/program/libmergedlo.so(_ZN11Application7ExecuteEv+0x45)[0x7f80bea14d35]
/usr/lib/libreoffice/program/libmergedlo.so(+0x21cdc2b)[0x7f80bda66c2b]
/usr/lib/libreoffice/program/libmergedlo.so(_Z10ImplSVMainv+0x51)[0x7f80bea1c731]
/usr/lib/libreoffice/program/libmergedlo.so(soffice_main+0xa3)[0x7f80bda80523]
/usr/lib/libreoffice/program/soffice.bin(+0x10b0)[0x55edfc86e0b0]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f80bb656083]
/usr/lib/libreoffice/program/soffice.bin(+0x10ee)[0x55edfc86e0ee]
```

I think I can mostly reproduce it with libreoffice 7.3, and it is consistently crashing with the version in PPA right now (`1:7.3.3~rc2-0ubuntu0.22.04.1~lo1`), **if  I install the -nogui packages**, and only in that case.

The solution is to install the full version with GUI support.

**Comment by floretn** [comment]
Hello! I have the same problem. 

What I do: I copy the server.py and converter.py into my Docker container. After that I start server.py inside container and call converter.py from my project. But if I create a lot of users by jmeter to my project, the server.py break with the same stack trace.

How I can fix the problem?

**Comment by regebro** [comment]
@floretn Have you installed the full version of libreoffice or just the -nogui packages?

**Comment by floretn** [comment]
> Is it for any document or a specific one?

For any document. I need to create converter-service from any type to PDF.
I've solved the problem by starting server.py into cycle while(true) :)

**Comment by regebro** [comment]
Huh, well, it's some sort of Libreoffice bug, that's for sure. It's a weird one.

**Comment by damian66** [comment]
@Rafiot I found some questions with similar error and they may be related to the corrupted LibreOffice user profile files. Basically, what I saw, the solution was to completely remove LibreOffice and install it again... 

- https://bugs.launchpad.net/ubuntu/+source/libreoffice/+bug/1922112
- https://forum.openoffice.org/en/forum/viewtopic.php?f=16&t=53761 <- this one is 10 years old 🧐
