### ISSUE TITLE
[Feature Request] Add as formula to HomeBrew

### ISSUE THREAD

**Issue by andrewcrook** [unoconv/unoserver#39]
Add as formula to HomeBrew

Can also probably add LibraOffice as a dependency to be automatically installed when installing the unoserver package.
Could also add support for brew-service as an option to automatically set up a launchd plist and start and stop as a daemon.

**Comment by regebro** [comment]
I haven't got the slightest clue how to do that, and I do not have the time to learn it, sorry.
