### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by bebo-dot-dev** [unoconv/unoserver#43]
Hi there, great project thank you, one small issue here. When testing install and usage on Linux Mint 20.3 by following [the install instructions in the readme.md](https://github.com/unoconv/unoserver/blob/1.2/README.rst#installation), I found that the two installed scripts ended up with a top line shebang that looks like:

```
#!/opt/libreoffice7.2/program/python.bin
```
..and then found that the two installed scripts refuse to work unless changed to:
```
#!/opt/libreoffice7.2/program/python
```
I'm testing with Libreoffice v7.2.7 stable.

Not a showstopper but any idea what might be happening to cause this?

**Comment by bebo-dot-dev** [comment]
A bit more to add, I tested further with a Ubuntu 22.04 Docker image and everything installed and worked perfectly with no issues. 

The difference with the Docker test is that I apt-get installed Libreoffice, wget, pip and unoserver within a Dockerfile and the end result was Libreoffice 7.3.5.2 installed along with the Libreoffice sdk using the system /usr/bin/python3. pip install unoserver happily detected everything and installed as expected with no issues with this setup.

My earlier testing with Linux Mint was with manually downloaded .deb packages for Libreoffice and the Libreoffice sdk, I'm not sure why the unoserver install doesn't work as smoothly and easily as with a Libreoffice apt-get install but no dramas, Docker is what I was aiming for anyway.

I'll live this open for visibility but feel free to close it if you want to.

**Comment by regebro** [comment]
It seems that pip gets the wrong path to the python executable, for some reason. I don't know much about the internals of packaging but I would think it's a bug or a quirk of the Linux Mint LibreOffice packages.

**Comment by bebo-dot-dev** [comment]
Hi @regebro thanks for replying, I think you're right, there's something odd going on with the LO .deb packages when they're installed manually in Linux Mint. Not a problem (for me).
