### ISSUE TITLE
Bring back the index refresh support

### ISSUE THREAD

**Issue by AlePini** [unoconv/unoserver#48]
One of the features I miss from the old unoconv, is the automatic update of indexes and ToC before the conversion.
I created a branch, where I re-added the `for cicle` needed to refresh the indexes. And it just works !

I hope you can bring back this feature in a future release!

**Comment by vijayarun** [comment]
Any update on this enhancement

**Comment by AlePini** [comment]
> No, but if @AlePini (or anyone else) makes a pull request that implements it, it would go faster. :-D

Sorry about the delay, I just made the pull request. Hope it works!
