### ISSUE TITLE
how to convert xlsx to csv - and custom filters(settings)

### ISSUE THREAD

**Issue by freexmonster** [unoconv/unoserver#56]
Good afternoon, I can not figure out how to transfer the settings for conversion.

https://help.libreoffice.org/latest/en-US/text/shared/guide/csv_params.html

csv:Text - txt - csv (StarCalc):44,34,,1,,,,true,,,true

unoconvert  --convert-to  csv ......

Need help!

**Comment by regebro** [comment]
Unoconvert does not yet support specific settings.

**Comment by unthank** [comment]
Great addition to the package! I would need some guidance on the syntax for filter-option please. From using libreoffice in normal headless mode, I would have expected
`unoconvert --convert-to csv --filter-options "Text - txt - csv (StarCalc)"="59,34,76,," infile.xlsx outfile.csv`
to produce a semicolon-separated file, this is however not the case. Do the 5-15 CSV filter tokens need to be addressed individually? And if so, is there a definition of the namespace somewhere?

Thanks!
