### ISSUE TITLE
documentation: Unclear usage for unoserver to convert documents

### ISSUE THREAD

**Issue by amas0** [unoconv/unoserver#6]
It is not currently clear from the README how one uses the `unoserver` script to actively convert office documents. Usage only covers starting the server from the command line but not how one passes files for conversion to the server. This is more obvious in `unoconvert`, where `infile` and `outfile` are clear arguments.

It would be helpful for users if that usage information were included in the documentation.

**Comment by WilliamDEdwards** [comment]
You pass files to `unoconverter`, which passes files to the server you started with `unoserver`. There are no files to pass directly to `unoserver`.

**Comment by regebro** [comment]
Yes, unoconvert uses the unoserver to convert.
