### ISSUE TITLE
xlsx to pdf convert - consider the local date format

### ISSUE THREAD

**Issue by jankokert** [unoconv/unoserver#66]
I managed to convert an xlsx file to pdf on my remote Ubuntu machine (no UI). (Great tool btw!)

But one minor issue remains:
In the xlsx file I defined a border that contains the current date (`&d`).
When I open the file in LibreOffice the date is correctly displayed in the local format (German, `17.03.2023`).
However, on the server where I'm running `unovoncert`, the date in the pdf file is rendered in the American format. (`03/17/2023`)
I checked the timezone settings on the server with `timedatectl` and I got `Europe/Berlin` (which is correct!)

- So how can I tell LibreOffice to use the local setting (headless, via command line/putty)
- Or how can I tell `unovoncert` to use this timezone?

Thank you very much in advance!

**Comment by regebro** [comment]
Can you give me an example file, because I don't know how you replicate this?
