### ISSUE TITLE
Is it possible to specify additional export filters with unoserver?

### ISSUE THREAD

**Issue by ezhikov** [unoconv/unoserver#7]
Hello!

My goal is to create tagged PDF documents and right now I'm using unoconv to convert programmatically created fodt documents to pdf. With unoconv I can specify export filters like `UseTaggedPDF=true` and `SelectPdfVersion=2`, but can't find how to supple same filters to unoconvert. Is it possible crrently? If not, do you have plans to implement it? I'm not really familiar with python and UNO, but I'm willing to contribute, if you provide some guidance.

**Comment by gulien** [comment]
👍 

The following flags would also help me to switch to `unoserver` in [Gotenberg](https://gotenberg.dev):

* `--printer PaperOrientation=landscape`
* `--export PageRange=...`

**Comment by regebro** [comment]
We definitely want to implement some more flags, but are waiting to see which ones are requested a lot. These seem to be good candidates. We'll look into that.

**Comment by gulien** [comment]
@regebro a way would be to offer a sort of "passthrough" flag, so that you don't have to maintain an exhaustive list, i.e.:

```
--uno-args="-env:UserInstallation=//file://tmp/foo"
```

**Comment by gulien** [comment]
Indeed, good point; I've been playing with LibreOffice headless lately, and I totally missed the fact you are using `uno` for interacting with it 😄

**Comment by regebro** [comment]
The next version of unoserver will support a --filter-options parameter.
