### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by matheusrps** [unoconv/unoserver#74]
Is there any workaround for soffice.bin process to not leak memory? I've an api that converts pptx, I setup a flask server with gunicorn and 4 workers, all works fine except that soffice.bin just keeps using more and more memory, it starts about 1gb and after 4 hours its already consuming 2gb. Is there a way that it just kill this process and start over again after some time or some way to stop this leak?

**Comment by regebro** [comment]
From our perspective there is nothing we can do. When it comes to size, it will increase in size with larger documents, and it will not release that when that conversion is done, but it will then not increase further with small documents. So don't worry that it's using 2gb after an hour, that doesn't sound that much.

But restarting once every 24 hours is not uncommon. We make new software releases wich will restart the servers including Libreoffice typically once every night, and I think that's my the memory leaks doesn't affect us.
