### ISSUE TITLE
Cancel ongoing conversion

### ISSUE THREAD

**Issue by gulien** [unoconv/unoserver#8]
Hello 👋 

Thanks for maintaining `unoconv` and working on this new tool 👍 

**Q:** How to cancel an ongoing conversion with `unoserver`?

Currently, in [Gotenberg](https://gotenberg.dev), I kill the `unoconv` process, which also kills the child processes. Killing the `unoconvert` process would be enough?

**Comment by regebro** [comment]
No, I think you would have to kill the unoserver process. That should kill the Libreoffice which is the process doing the actual conversion.

**Comment by gulien** [comment]
👍 Indeed, that makes sense.
