### ISSUE TITLE
unable to start UnoServer from python

### ISSUE THREAD

**Issue by sadaqabdo** [unoconv/unoserver#88]
Hello,

I'm attempting to run UnoServer from inside a ubuntu20.04 docker container with python . I've ensured that the required libraries are installed in the image `libreoffice` and `default-jre-headless`.

When I execute UnoServer using the subprocess module as shown below, it works perfectly:

```python
import subprocess
CMD = ["unoserver"]
result = subprocess.run(CMD)
````

However, a problem arises when I use the native Python approach:
```python
from unoserver.server import UnoServer
unoserver = UnoServer()
unoserver.start()
```

This results in the following error:
```bash
javaldx failed!
Warning: failed to read path from javaldx
LibreOffice 6.4 - Fatal Error: The application cannot be started. 
[context="user"] caught unexpected com.sun.star.ucb.ContentCreationException: Cannot create folder (invalid path): 'None'
```
any idea why it crashes and how can I achieve it?
Thanks

**Comment by regebro** [comment]
I would recommend to not start it from Python. It will not only soon become harder, there's really no point in doing that.
