### ISSUE TITLE
Why --uno-interface defaulting to --interface value instead of 127.0.0.1

### ISSUE THREAD

**Issue by HirotoKagotani** [unoconv/unoserver#96]
When I run unoserver as:
    # unoserver --interface 0.0.0.0
I find the LibreOffice server is waiting for connection at 0.0.0.0:2002.

I understand that the --uno-interface value is used for communication between unoserver and the LibreOffice server, and that both typically run on the same host. In that case, it seems better that the default value of --uno-interface should always be 127.0.0.1, regardless of the value of --interface.

**Comment by regebro** [comment]
Yeah, that makes sense.

**Comment by regebro** [comment]
2.0.1 released
