### ISSUE TITLE
The value of --host-location ignored for outfile

### ISSUE THREAD

**Issue by HirotoKagotani** [unoconv/unoserver#97]
When I install and run unoserver and LibreOffice on a VirtualBox guest machine, then I run unoconvert on the VirtualBox host:
    # unoconvert --host-location remote --host 127.0.0.1 sample.docx sample.pdf
the outfile "sample.pdf" is created in the guest machine. (Note: port 2003 is forwarded to the guest machine)

The outpath argument for the remote methods convert() and compare() should be None when self.remote is True.

**Comment by regebro** [comment]
Good point, I had not considered the context of port forwarding.

**Comment by regebro** [comment]
2.0.1 released
